### ISSUE TITLE
TypeError: Illegal access to a strict mode caller function

### ISSUE THREAD

**Issue by Amberlamps** [desmondmorris/node-twitter#60] opened 2015-01-08 10:05 UTC
When I am trying to use this module in strict mode:

node_modules\twitter\lib\twitter.js 161
  if (typeof Twitter.prototype[arguments.callee.caller.name] !== 'undefined')
                                               ^
TypeError: Illegal access to a strict mode caller function.
    at Twitter.get (c:\Users\Alexander\node_projects\xxx\node_modules\twtter\lib\twitter.js:161:48)
    at getLists (c:\Users\Alexander\node_projects\xxx\lib\jobs\getCountresFromLists.js:27:14)
    at getCountriesFromLists (c:\Users\Alexander\node_projects\xxx\lib\jbs\getCountriesFromLists.js:23:5)
    at Object.<anonymous> (c:\Users\Alexander\node_projects\xxx\test\getCountriesFromListsTest.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by desmondmorris** [comment] 2015-01-08 14:33
Duplicate of https://github.com/desmondmorris/node-twitter/issues/51.  This is resolved in the latest release [1.0.2](https://www.npmjs.com/package/twitter)

**Closed by desmondmorris** 2015-01-08 14:33 UTC
