### ISSUE TITLE
Listening to user is followed event 

### ISSUE THREAD

**Issue by larzuk91** [desmondmorris/node-twitter#104] opened 2015-07-23 03:08 UTC
I'm trying to listen via user stream the "user is followed" event in order to notify when my account gets a new follower accordingly to this page: https://dev.twitter.com/streaming/overview/messages-types#Events_event

I don't know if I'm doing something wrong or it's the module. My code is like follows:

var twitterClient = new Twitter({...});

twitterClient.stream('user', {'with':'user'},  function(stream){
        stream.on('data', function(event) {
            console.log(event);
        });

        stream.on('error', function(error) {
            console.log(error);
        });
    });

Actually I get some things like friends id's but nothing about new followers :( 

is there a solution ? Thanks in advance.

**Comment by Roach** [comment] 2015-08-21 01:22
This might be helpful: https://github.com/Roach/node-twitter-contributors/blob/master/daemon.js#L178-L190

**Comment by desmondmorris** [comment] 2016-05-23 01:20
This is a dupe of #90

**Closed by desmondmorris** 2016-05-23 01:20 UTC
